export default function DefaultTags() {
  return (
    <>
      <link rel="icon" type="image/x-icon" href="favicon.ico" />
      <meta
        name="keywords"
        content="warehouse, logistics, supplychain, transportation, shipping, business, warehousing, freight, storage, industrial, construction, realestate, cargo, trucking, transport, manufacturing, trucks, forklift, export, delivery, office, import, logisticsmanagement, logisticscompany, logistica, distribution, freightforwarding, logistic, work, gudang, управление, логистика, склад, менеджмент, перевозки, доставка, сервис, графики, авторизация, регистрация, складтканейвмоскве, складнойковрик, складдверей, складскаялогистика, складныедвери, складнаякушетка, складнойстол, складская, складшымкент, складскаяраспродажа, складной, складскоеоборудование, складнойстул, складные, склад1, складткани, складмосква, складигрушек, складскойкомплекс, складтканейвиталии, склад, складнойнож, складныеножи, складываемвещи, складчикова, складобуви, склады, складник, складскаякостанай, складмебели, складнойвелосипед, складцветов, складтканей, складскаятехника, склад1ash, складка, складнаямебель, складмебель, складодежды, складноймассажныйстол, менеджмент, менеджменткачества, менеджменторганизации, менеджментсалона, менеджменткиноактера, менеджментбудущего, менеджмента, менеджментвобразовании, менеджментжизни, менеджментвмедицине, менеджментсуществует, менеджментсалонакрасоты, менеджментякутск, менеджментартиста, менеджменту, менеджментспа, менеджментскд, менеджментзед, менеджментказино, менеджментвэд, менеджментсалоновкрасоты, менеджментпроекта, менеджменталматы, менеджментвспорте, менеджменткарьеры, менеджментмероприятий, менеджментвладикавказ,учет, альянсгео, home, экспертиза, услуги, собственность, план, межевание, инженер, екб, дача, гараж, likes, съемка, росреестр, перепланировка, машина, земля, екатеринбург, граница, архитектура, instadaily, участок, строительство, риэлтор, недвижимость, кадастр, здание, дом,supplychain, logistics, transportation, shipping, supplychainmanagement, freight, cargo, business, warehouse, trucking, transport, logisticsmanagement, logisticscompany, export, import, freightforwarding, b, warehousing, manufacturing, airfreight, covid, freightforwarder, procurement, trucks, seafreight, logistica, supplychainsolutions, delivery, ecommerce, truckdriver"
      />
    </>
  )
}
